### ISSUE TITLE
Pull time-tracking functionality out of the UI

### ISSUE THREAD

**Issue by mbrezinsky-revenyou** [istfariat/timer_winforms#1]
As the first iteration it can be put into some `Tracker` class, that will give an interface for controlling the current tracker. Nothing fancy, simple start/stop kind of methods.
History might be exposed for now probably. This way forms can still display data, and chances are there's no need for any further decoupling.
Even this small change will already be a huge improvement in separating the presentation layer from the tracking internals.

Proposed interface is something like:
```csharp
interface ITracker
{
  void Start(string tag);  // creates new entry in history, starting now, tagged with the given string
  void Pause(); // stops tracking, current interval's end time is set to now
}
```

As can be seen, it implies changing the data model so that the tag is a single piece of text. That shouldn't be a hard change, just drop the other two fields. No splitting or parsing is needed for now, just assume that the tag is one word at all times.

There will be one instance of this tracker per whole program, might be a static field on the program's main class even. UI then just calls these methods whenever user clicks some buttons. Since history can not change between these calls, just call the history refill method from the same handlers.

**Comment by istfariat** [comment]
program logic moved to new class
