### ISSUE TITLE
Move platform-specific stuff to a separate file

### ISSUE THREAD

**Issue by mbrezinsky-revenyou** [istfariat/timer_winforms#2]
Platform- specific stuff should live outside of platform-independent logic.
Everything P/Invoke & WinAPI can go to a separate file. Whenever support is needed for a new platform (which might simply be a different version/level of WinAPI), that can be done as another implementation of the same interface.

Proposed approach is to have an interface called `IPlatform` (or some such), which declares all the methods that time tracking logic needs to function (e.g. `GetCurrentWindowTitle()`, `GetLastInputTime()`). The time-tracking part then is less dependent on exact data structures and only dependent on higher-level concepts.

Of course, this can be done without explicitly declaring interfaces. It could be just a separate class (`Platform`? `Windows`? can't use "system" as it is taken by C#) that inherits from nothing.

**Comment by istfariat** [comment]
done
