### ISSUE TITLE
Make use of `foreach` where appropriate

### ISSUE THREAD

**Issue by mbrezinsky-revenyou** [istfariat/timer_winforms#4]
There are places, like `TimeTracker.SaveEntry()` where it would be more appropriate to use `foreach` over a collection or a view of it, rather than plain `for` with a counter from zero to count.

Revisit the code and change loop type where needed.

**Comment by istfariat** [comment]
two FORs changed to FOREACH third one in  ShowHistory() going backwards so it is not worth it
